### ISSUE TITLE
Content Enhancement : Linear Regression

### ISSUE THREAD

**Issue by AM1CODES** [OneStep-elecTRON/ContentSection#10]
The theory part for the Linear regression in Easy track is not up to the mark from the feedbacks that we have received. Hence, we are trying to upgrade it and make it better. Additions that we are planning to make - 

* Theory -  Content that's easy to understand and hits on the important and core topics of Linear Regression.
* Math - Inclusion of the complete math of Linear Regression along with examples.

**Comment by Anjali001** [comment]
@AM1CODES  Hey! I can help you improve the content. I was thinking to first write about linear regression in terms of statistics (like it determines relationship between dependent and independent variable) , specify the assumptions(important point which is missing in the content) and then giving proper formulae. If you think it's right, can you assign this issue to me? Also, is there any word limit that you've in mind?

**Comment by AM1CODES** [comment]
Hey  @Anjali001 ! I think the solution that you mentioned would cover all the aspects of Linear regression that we need. I will assign you the issue so that you can start working on it. You can ping us here about your progress or you can join our discord server and talk to us over there if you have any issues. All the best!

**Comment by Anjali001** [comment]
@AM1CODES  Sure. I'm already on the channel, I'll contact you on Discord , in case I have any questions. 
Thanks.

**Comment by AM1CODES** [comment]
Sure.

**Comment by AM1CODES** [comment]
@Anjali001 Any updates on the progress?

**Comment by Anjali001** [comment]
@AM1CODES Yeah. It's mostly done. I guess I'll make PR in a day or two.

**Comment by AM1CODES** [comment]
@Anjali001 Thank You. We will review it. Run some plagiarism checks on it and if all is good, it will be merged  very soon.

**Comment by Anjali001** [comment]
@AM1CODES 
Is everything fine with the theory part? Let me know if you require any changes.

**Comment by AM1CODES** [comment]
@Anjali001 I am really sorry for this late reply. We actually had our end sem exams going on so we were a little busy with that. @amansharma2910 will review the write up asap and we can then merge it or make the required changes.

**Comment by Anjali001** [comment]
@AM1CODES it's okay. Take your time. Let me know if there's any problem.

**Comment by amansharma2910** [comment]
Hi @Anjali001. I have requested a few minor changes on the PR. Please look into it. Great content btw. The explanation is perfect and really to the point.

**Comment by AM1CODES** [comment]
@Anjali001  Any updates on the content?

**Comment by Anjali001** [comment]
@AM1CODES 
Yes, I updated it yesterday. Have tagged @amansharma2910 in the message on the pull request.

**Comment by Anjali001** [comment]
@AM1CODES @amansharma2910 
Hey, do you require any change on the linear regression content?

**Comment by amansharma2910** [comment]
@Anjali001 no changes required on your end. I'll make a few minor edits directly on my end and merge the PR. Great work!

**Comment by amansharma2910** [comment]
@Anjali001 merged your PR. Thanks for your contribution to OneStepML! Feel free to share your achievement on LinkedIn and Twitter.
