### ISSUE TITLE
Found a typo in SVM.md

### ISSUE THREAD

**Issue by SuhasBRao** [OneStep-elecTRON/ContentSection#18]
Hello there,  I found a small typo in SVM.md thought of fixing it. I have gone through Contributing Guidelines.
Here's a snapshot of the typo I found.

![Screenshot (118)_LI](https://user-images.githubusercontent.com/65769327/120160371-cfb75d80-c213-11eb-957a-7cddeb820cd6.jpg)

I think it must be 'SVM are used mostly for classification type ***problems***'.
I would like to fix this issue.

**Comment by AM1CODES** [comment]
Hey @SuhasBRao Thank you for going through the contents and informing us about this typo. I think you have already made a PR for this issue and i will take a look at it asap.

**Comment by SuhasBRao** [comment]
Thank you for reviewing the issue.

**Comment by SuhasBRao** [comment]
Hey there, I found few more typos and corrected them. I have made a PR please do review it.

**Comment by AM1CODES** [comment]
Sure i will review it asap.

**Comment by amansharma2910** [comment]
@SuhasBRao reviewed the changes. The PR has been merged. Thanks for your contribution.
